{
 "title": "Reactive Account OpenAPI Benchmarks",
 "description": "Generic dashboard for Quarkus apps",
 "tags": [
  "quarkus",
  "java"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "default" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(process_uptime_seconds{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_uptime_seconds{namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{pod=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_cpu_usage{pod=\"$instance\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem",
   "type": "gauge",
   "description": "Used / max heap memory",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=\"$instance\"}*100)/sum(jvm_memory_max_bytes{pod=\"$instance\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Num of Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\"}[1m])))/60",
     "legendFormat": "Requests per Second"
    },
    {
     "expr": "round(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\"}[$__range])))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "% failed",
   "type": "gauge",
   "description": "Failed requests in last 1 minute",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(locust_stats_num_failures{path=\"Aggregated\"}[1m]) * 100 /rate(locust_stats_num_requests{path=\"Aggregated\"}[1m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "% failed",
   "type": "gauge",
   "description": "failure rate by Locust",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(locust_fail_ratio[5m])",
     "legendFormat": " "
    }
   ]
  },
  { "title": "HTTP (cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Avg server response times",
   "type": "graph",
   "description": "HTTP average response times over last [1m] for all instances in a cluster.\n\nPlease mind that response time displayed here is measured inside JVM, it is not full end to end latency your users see, which can be few times bigger.\n\nAdd this to your application.properties first:\nquarkus.resteasy.metrics.enabled=true",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{status=~\"2..\", uri=~\"/accounts.*\"}",
     "legendFormat": "current"
    },
    {
     "expr": "avg_over_time(http_server_requests_seconds_max{status=~\"2..\", uri=~\"/accounts.*\"}[15m])",
     "legendFormat": "15 min avg"
    }
   ]
  },
  { "title": "Hardware utilisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(system_cpu_usage{pod=\"$instance\"})",
     "legendFormat": "Usage for the JVM process. 100% means that all CPUs were actively running threads from the JVM"
    },
    {
     "expr": "sum(avg_over_time(system_cpu_usage{pod=\"$instance\"}[15m]))"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(system_load_average_1m{pod=\"$instance\"})",
     "legendFormat": "Load average 1 min"
    },
    {
     "expr": "sum(avg_over_time(system_load_average_1m{pod=\"$instance\"}[15m]))",
     "legendFormat": "Load average 15 mins"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "Live threads $instance" },
    { "expr": "jvm_threads_peak_threads", "legendFormat": "Peak threads $instance" }
   ]
  },
  { "title": "Datasource (Agroal)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "JDBC connection pool active / awaiting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "agroal_active_count{service=\"accounts\"}",
     "legendFormat": "Active $instance"
    },
    {
     "expr": "agroal_awaiting_count{service=\"accounts\"}",
     "legendFormat": "Awaiting $instance"
    }
   ]
  },
  {
   "title": "Timing for database quries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "app_db_query_duration_seconds_bucket",
     "legendFormat": "Time to acquire a connection"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Durations over last [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (increase(jvm_gc_pause_seconds_count{pod=\"$instance\"}[1m]))",
     "legendFormat": "Approximate accumulated collection elapsed time ({{name}})"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } }
 ]
}