resources:
  - ../../base
  - service.yaml

namespace: prometheus

patchesJSON6902:
- target:
    group: monitoring.coreos.com
    version: v1
    kind: Prometheus
    name: prometheus
  patch: |-
    - op: replace
      path: /spec/storage/volumeClaimTemplate/spec/storageClassName
      value: local-path
