---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-load-gen
spec:
  selector:
    matchLabels:
      app: api-load-gen
  template:
    metadata:
      labels:
        app: api-load-gen
    spec:
      containers:
        - name: locust
          image: gcr.io/vino9-276317/api-load-gen
          ports:
            - containerPort: 8089
              protocol: TCP
          env:
            - name: HOST
              value: "http://accounts:8080"
            - name: USERS
              value: "10"
            - name: WORKERS
              value: "2"
            - name: WORKER_PARAMS
              value: "--sleep 500 --random-id"
              # value: "--sleep 500 --data /data/test_data.csv"
          volumeMounts:
            - mountPath: /data
              name: testdata-pv
      volumes:
        - name: testdata-pv
          persistentVolumeClaim:
            claimName: testdata-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: api-load-gen
  labels:
    app: api-load-gen
spec:
  type: NodePort
  selector:
    app: api-load-gen
  ports:
    - name: http
      port: 8089
      nodePort: 30902
