apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-load-gen
spec:
  selector:
    matchLabels:
      app: api-load-gen
  template:
    metadata:
      labels:
        app: api-load-gen
    spec:
      containers:
        - name: locust
          image: gcr.io/vino9-276317/api-load-gen
          ports:
            - containerPort: 8089
              protocol: TCP
            - containerPort: 9646
              protocol: TCP
          env:
            - name: HOST
              value: "http://accounts:8080"
            - name: USERS
              value: "10"
            - name: WORKERS
              value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: api-load-gen
  labels:
    app: api-load-gen
spec:
  type: LoadBalancer
  selector:
    app: api-load-gen
  ports:
    - name: http
      port: 8089
    - name: metrics
      port: 9646
